version: 3

services:
    feeds:
        image: fotofamilia
        build: ./dockerfiles/servicos/
        hostname: feeds
        expose:
            - "5000"
        volumes:
            - "./feeds:/servico"
        command: python3 servico.py
        networks:
            fotofamilianet:
                ipv4_address: 172.29.1.1

    comentarios:
        image: fotofamilia
        build: ./dockerfiles/servicos/
        hostname: comentarios
        expose:
            - "5000"
        volumes:
            - "./comentarios:/servico"
        command: python3 servico.py
        networks:
            fotofamilianet:
                ipv4_address: 172.29.1.2

    likes:
        image: fotofamilia
        build: ./dockerfiles/servicos/
        hostname: likes
        expose:
            - "5000"
        volumes:
            - "./likes:/servico"
        command: python3 servico.py
        networks:
            fotofamilianet:
                ipv4_address: 172.29.1.3
    bancodados:
        image: mysql
        hostname: bancodados
        expose:
          - "3606"
        environment:
            MYSQL_ROOT_PASSWORD: admin
        networks:
            fotofamilianet:
                ipv4_address: 172.29.1.4

    arquivos:
        image: arquivos
        build: ./dockerfiles/nginx/
        volumes:
            - "./assets/imagens:/usr/share/nginx/html"
        hostname: arquivos
        expose:
          - "80"
        networks:
            fotofamilianet:
                ipv4_address: 172.29.1.5

networks:
    fotofamilianet:
        ipam:
          driver: default
          config:
              - subnet: 172.29.1.0/16